---
- name: Workers configuration
  hosts: kmaster_main
  tasks:

      #Convierto el comando para unir a los nodos trabajadores en un objeto de ansible.
    - name: Get join command 
      shell: grep -e 'kubeadm join [[:print:]]*' cluster_initialized.log | grep -v "control-plane"
      register: workers_join_command_raw

      #Creo una variable global de asnible cuyo contenido será el contenido del atributo del objeto que contiene la información que necesito: el mandato para unir los nodos trabajadores.
    - name: Make variables global
      set_fact:
        workers_join_command: "{{ workers_join_command_raw.stdout_lines[0] }}"

- name: Workers configuration
  hosts: worker_nodes
  tasks:

      #Uno los nodos trabajadores y guardo el resultado en un log.
    - name: Join control plane
      shell: "{{ workers_join_command }} >> {{ user_home }}/cluster_joined_worker.log"
      become: true