inner_pod_network: "172.16.0.0/16"
triggera_operator_yaml_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml"
calicoctl_binary_url: "https://github.com/projectcalico/calico/releases/download/v3.28.0/calicoctl-linux-amd64"